/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PresencasRouteImport } from './routes/presencas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencasRoute = PresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financas': typeof FinancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/presencas': typeof PresencasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financas': typeof FinancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/presencas': typeof PresencasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/financas': typeof FinancasRoute
  '/pagamentos': typeof PagamentosRoute
  '/presencas': typeof PresencasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/colaboradores'
    | '/financas'
    | '/pagamentos'
    | '/presencas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/colaboradores'
    | '/financas'
    | '/pagamentos'
    | '/presencas'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/colaboradores'
    | '/financas'
    | '/pagamentos'
    | '/presencas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  FinancasRoute: typeof FinancasRoute
  PagamentosRoute: typeof PagamentosRoute
  PresencasRoute: typeof PresencasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presencas': {
      id: '/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof PresencasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  FinancasRoute: FinancasRoute,
  PagamentosRoute: PagamentosRoute,
  PresencasRoute: PresencasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
